// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: extension.proto

package org.canoegame.entity;

public final class Extension {
  private Extension() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(org.canoegame.entity.Extension.database);
    registry.add(org.canoegame.entity.Extension.table);
    registry.add(org.canoegame.entity.Extension.pk);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int DATABASE_FIELD_NUMBER = 71001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> database = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int TABLE_FIELD_NUMBER = 71002;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.String> table = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  public static final int PK_FIELD_NUMBER = 72001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.Boolean> pk = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017extension.proto\022\006entity\032 google/protob" +
      "uf/descriptor.proto:3\n\010database\022\037.google" +
      ".protobuf.MessageOptions\030\331\252\004 \001(\t:0\n\005tabl" +
      "e\022\037.google.protobuf.MessageOptions\030\332\252\004 \001" +
      "(\t:+\n\002pk\022\035.google.protobuf.FieldOptions\030" +
      "\301\262\004 \001(\010B\026\n\024org.canoegame.entityb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    database.internalInit(descriptor.getExtensions().get(0));
    table.internalInit(descriptor.getExtensions().get(1));
    pk.internalInit(descriptor.getExtensions().get(2));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
