// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test1.proto

package org.canoegame.example;

public interface HelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Hello)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string greeting = 1;</code>
   * @return The greeting.
   */
  java.lang.String getGreeting();
  /**
   * <code>string greeting = 1;</code>
   * @return The bytes for greeting.
   */
  com.google.protobuf.ByteString
      getGreetingBytes();
}
