// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.canoegame.example;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>.protocol.Hello hello = 4;</code>
   * @return Whether the hello field is set.
   */
  boolean hasHello();
  /**
   * <code>.protocol.Hello hello = 4;</code>
   * @return The hello.
   */
  org.canoegame.example.Hello getHello();
  /**
   * <code>.protocol.Hello hello = 4;</code>
   */
  org.canoegame.example.HelloOrBuilder getHelloOrBuilder();
}
