// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package org.canoegame.example;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\010protocol\032\017extension.proto\032" +
      "\013test1.proto\"[\n\006Person\022\014\n\004name\030\001 \001(\t\022\n\n\002" +
      "id\030\002 \001(\005\022\r\n\005email\030\003 \001(\t\022\036\n\005hello\030\004 \001(\0132\017" +
      ".protocol.Hello:\010\312\325\"\004haha*+\n\tPhoneType\022\n" +
      "\n\006MOBILE\020\000\022\010\n\004HOME\020\001\022\010\n\004WORK\020\002B\031\n\025org.ca" +
      "noegame.exampleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.canoegame.entity.Extension.getDescriptor(),
          org.canoegame.example.Test1.getDescriptor(),
        });
    internal_static_protocol_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Person_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Hello", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(org.canoegame.entity.Extension.database);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    org.canoegame.entity.Extension.getDescriptor();
    org.canoegame.example.Test1.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
